"""
ArthoBodh: Bengali Word Sense Disambiguation (WSD) System
Generates the comprehensive, self-contained Google Colab Notebook: ArthoBodh_WSD_Colab.ipynb
"""

import json
import os

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# **ArthoBodh: Bengali Word Sense Disambiguation (WSD) System**\n",
                "### **A Deep Learning & Classical NLP Benchmark on the Bengali WSD Dataset**\n",
                "\n",
                "**Authors / Project:** ArthoBodh NLP Research  \n",
                "**Task:** Given a Bengali context sentence and an ambiguous target word, predict the intended sense:  \n",
                "$$\\text{Context } C + \\text{Target Word } w \\longrightarrow \\text{Sense } s \\in S(w)$$\n",
                "\n",
                "---\n",
                "### **Pipeline Overview**\n",
                "1. **Environment Setup & GPU Detection**\n",
                "2. **Stage 1: Dataset Loading & Parsing** (100 polysemous words, 345 sense definitions)\n",
                "3. **Stage 2: Statistical Inspection & Visualizations**\n",
                "4. **Stage 3: Problem Formulation & Bengali Preprocessing**\n",
                "5. **Stage 4: TF-IDF + Linear SVM Baseline** (Lexical Sample WSD Formulation)\n",
                "6. **Stage 5 & 6: Pretrained Bengali Transformer (`csebuetnlp/banglabert`) Fine-Tuning**\n",
                "7. **Stage 7: Final Held-Out Test Evaluation** (Overall + 3-Sense vs 4-Sense Complexity Breakdown)\n",
                "8. **Stage 8: In-Depth Error Analysis**\n",
                "9. **Stage 9: Model Comparison & Scientific Conclusions**\n",
                "10. **Model Saving & Artifact Export**"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Step 0: Environment Setup & GPU Check**\n",
                "Let us verify whether GPU acceleration (CUDA) is available in Google Colab (recommended: Runtime -> Change runtime type -> T4 GPU)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!pip install -q transformers torch scikit-learn matplotlib pandas numpy\n",
                "\n",
                "import torch\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "print(f\"Device in use:   {device}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"GPU Name:        {torch.cuda.get_device_name(0)}\")\n",
                "else:\n",
                "    print(\"Note: Running on CPU. For faster Transformer fine-tuning, enable T4 GPU under Runtime -> Change runtime type.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 1 & 2: Dataset Loading, Parsing & Inspection**\n",
                "The dataset consists of 100 Bengali polysemous words with 345 total sense definitions:\n",
                "* **55 words with 3 senses** (165 senses)\n",
                "* **45 words with 4 senses** (180 senses)\n",
                "* Each sense contains ~10 context paragraphs describing that specific sense.\n",
                "\n",
                "We parse the XML-style headers `<word-TARGET><senseN-DEFINITION>` and segment clean context examples."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import re\n",
                "import json\n",
                "import random\n",
                "from collections import Counter\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "# Set random seeds for reproducibility\n",
                "def set_seed(seed=42):\n",
                "    random.seed(seed)\n",
                "    np.random.seed(seed)\n",
                "    torch.manual_seed(seed)\n",
                "    if torch.cuda.is_available():\n",
                "        torch.cuda.manual_seed_all(seed)\n",
                "set_seed(42)\n",
                "\n",
                "# Locate dataset directory (supports zip upload or unzipped folder)\n",
                "import zipfile, glob\n",
                "for z_path in glob.glob('*.zip') + glob.glob('/content/*.zip'):\n",
                "    print(f'Found zip archive {z_path}, auto-extracting...')\n",
                "    with zipfile.ZipFile(z_path, 'r') as zf:\n",
                "        zf.extractall('.')\n",
                "\n",
                "DATA_DIR = 'Database - Bengali Word Sense Disambiguation'\n",
                "if not os.path.exists(DATA_DIR):\n",
                "    if os.path.exists('/content/Database - Bengali Word Sense Disambiguation'):\n",
                "        DATA_DIR = '/content/Database - Bengali Word Sense Disambiguation'\n",
                "    elif os.path.exists('e:/ArthoBodh/Database - Bengali Word Sense Disambiguation'):\n",
                "        DATA_DIR = 'e:/ArthoBodh/Database - Bengali Word Sense Disambiguation'\n",
                "    else:\n",
                "        print(\"Please upload archive.zip or the 'Database - Bengali Word Sense Disambiguation' folder.\")\n",
                "\n",
                "def parse_header(header_line: str):\n",
                "    tags = re.findall(r'<([^>]+)>', header_line)\n",
                "    word, sense_def = None, None\n",
                "    for tag in tags:\n",
                "        t = tag.strip()\n",
                "        if t.startswith('word-') or t.startswith('word1-'):\n",
                "            word = re.sub(r'^word\\d*-', '', t).strip()\n",
                "        elif re.match(r'sense\\d+-', t):\n",
                "            sense_def = re.sub(r'^sense\\d+-', '', t).strip()\n",
                "    return word, sense_def\n",
                "\n",
                "def clean_bengali_text(text: str) -> str:\n",
                "    text = text.replace('\\ufeff', '').replace('\\u200b', '')\n",
                "    text = re.sub(r'[ \\t\\r\\f\\v]+', ' ', text)\n",
                "    lines = [l.strip() for l in text.split('\\n') if l.strip()]\n",
                "    return ' '.join(lines).strip()\n",
                "\n",
                "def load_dataset(data_dir):\n",
                "    folders = sorted([f for f in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir, f))])\n",
                "    records = []\n",
                "    catalog = {}\n",
                "\n",
                "    for folder in folders:\n",
                "        folder_path = os.path.join(data_dir, folder)\n",
                "        catalog[folder] = {'target_word': None, 'senses': {}}\n",
                "\n",
                "        for s_idx in [1, 2, 3, 4]:\n",
                "            sfile = f\"Sense{s_idx}.txt\"\n",
                "            fp = os.path.join(folder_path, sfile)\n",
                "            if not os.path.exists(fp) or os.path.getsize(fp) <= 3:\n",
                "                continue\n",
                "            with open(fp, 'r', encoding='utf-8-sig', errors='replace') as f:\n",
                "                content = f.read().strip()\n",
                "            if not content:\n",
                "                continue\n",
                "            paras = [p.strip() for p in re.split(r'\\n\\s*\\n', content) if p.strip()]\n",
                "            if not paras:\n",
                "                continue\n",
                "            first_lines = paras[0].splitlines()\n",
                "            w, s_def = parse_header(first_lines[0])\n",
                "            if catalog[folder]['target_word'] is None and w:\n",
                "                catalog[folder]['target_word'] = w\n",
                "            catalog[folder]['senses'][s_idx] = s_def\n",
                "\n",
                "            clean_paras = []\n",
                "            if len(first_lines) > 1:\n",
                "                body = '\\n'.join(first_lines[1:]).strip()\n",
                "                if body:\n",
                "                    clean_paras.append(body)\n",
                "            for p in paras[1:]:\n",
                "                clean_paras.append(p)\n",
                "\n",
                "            for p_i, p_text in enumerate(clean_paras):\n",
                "                clean_t = clean_bengali_text(p_text)\n",
                "                if clean_t:\n",
                "                    records.append({\n",
                "                        'folder': folder,\n",
                "                        'target_word': w,\n",
                "                        'sense_num': s_idx,\n",
                "                        'sense_label': s_idx - 1,  # 0-indexed\n",
                "                        'sense_def': s_def,\n",
                "                        'sense_id': f\"{folder}_S{s_idx}\",\n",
                "                        'text': clean_t,\n",
                "                        'char_len': len(clean_t),\n",
                "                        'word_len': len(clean_t.split())\n",
                "                    })\n",
                "    for r in records:\n",
                "        r['num_senses_for_word'] = len(catalog[r['folder']]['senses'])\n",
                "    return records, catalog\n",
                "\n",
                "records, catalog = load_dataset(DATA_DIR)\n",
                "print(f\"Successfully loaded {len(records)} context paragraphs across {len(catalog)} polysemous words.\")\n",
                "w3 = sum(1 for d in catalog.values() if len(d['senses']) == 3)\n",
                "w4 = sum(1 for d in catalog.values() if len(d['senses']) == 4)\n",
                "print(f\"Words with 3 senses: {w3} ({w3*3} sense definitions)\")\n",
                "print(f\"Words with 4 senses: {w4} ({w4*4} sense definitions)\")\n",
                "print(f\"Total unique sense definitions: {w3*3 + w4*4}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### **Dataset Statistical Analysis & Visualizations**\n",
                "We compute length statistics and plot:\n",
                "1. Word Complexity Distribution (3 vs 4 senses)\n",
                "2. Context Paragraph Lengths (in words and characters)\n",
                "3. Stratified Train / Validation / Test allocation"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "char_lens = [r['char_len'] for r in records]\n",
                "word_lens = [r['word_len'] for r in records]\n",
                "\n",
                "print(\"=== CONTEXT LENGTH STATISTICS ===\")\n",
                "print(f\"Character Length: Min={min(char_lens)}, Max={max(char_lens)}, Mean={np.mean(char_lens):.1f}, Median={np.median(char_lens):.1f}\")\n",
                "print(f\"Word Length:      Min={min(word_lens)}, Max={max(word_lens)}, Mean={np.mean(word_lens):.1f}, Median={np.median(word_lens):.1f}\")\n",
                "\n",
                "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n",
                "ax1.hist(word_lens, bins=25, color='#1f77b4', edgecolor='black', alpha=0.8)\n",
                "ax1.axvline(np.mean(word_lens), color='red', linestyle='--', label=f'Mean: {np.mean(word_lens):.1f}')\n",
                "ax1.axvline(np.median(word_lens), color='green', linestyle='-', label=f'Median: {np.median(word_lens):.1f}')\n",
                "ax1.set_title('Distribution of Context Lengths (Words)')\n",
                "ax1.set_xlabel('Words')\n",
                "ax1.set_ylabel('Count')\n",
                "ax1.legend()\n",
                "\n",
                "ax2.bar(['3-Sense Words', '4-Sense Words'], [w3, w4], color=['#2ca02c', '#d62728'], edgecolor='black', width=0.5)\n",
                "ax2.set_title('Polysemous Word Complexity Breakdown')\n",
                "ax2.set_ylabel('Number of Words')\n",
                "for i, v in enumerate([w3, w4]):\n",
                "    ax2.text(i, v + 1, f\"{v} words\", ha='center', fontweight='bold')\n",
                "ax2.set_ylim(0, 65)\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 3: Stratified Splitting & Preprocessing Inspection**\n",
                "### **Why Stratified Split per Sense?**\n",
                "Each sense has ~10 examples. To prevent data leakage while guaranteeing that **every sense** is present in training and rigorously tested, we perform a deterministic stratified split:\n",
                "- **Train (70%):** 7 examples per sense (2,416 total)\n",
                "- **Validation (10%):** 1 example per sense (345 total)\n",
                "- **Test (20%):** 2 examples per sense (690 total)\n",
                "\n",
                "The test set is **strictly held out** and never touched during training, model selection, or early stopping."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def create_stratified_splits(records, seed=42):\n",
                "    random.seed(seed)\n",
                "    groups = {}\n",
                "    for r in records:\n",
                "        groups.setdefault((r['folder'], r['sense_num']), []).append(r)\n",
                "\n",
                "    train, val, test = [], [], []\n",
                "    for key, items in sorted(groups.items()):\n",
                "        shuffled = list(items)\n",
                "        random.shuffle(shuffled)\n",
                "        n = len(shuffled)\n",
                "        n_test = max(1, round(n * 0.20))\n",
                "        n_val = max(1, round(n * 0.10))\n",
                "        n_train = n - n_test - n_val\n",
                "        if n_train <= 0: n_train = 1; n_val = 0\n",
                "\n",
                "        train.extend(shuffled[:n_train])\n",
                "        val.extend(shuffled[n_train:n_train + n_val])\n",
                "        test.extend(shuffled[n_train + n_val:])\n",
                "    return train, val, test\n",
                "\n",
                "train_records, val_records, test_records = create_stratified_splits(records, seed=42)\n",
                "print(f\"Train set:      {len(train_records)} instances ({len(train_records)/len(records)*100:.1f}%)\")\n",
                "print(f\"Validation set: {len(val_records)} instances ({len(val_records)/len(records)*100:.1f}%)\")\n",
                "print(f\"Test set:       {len(test_records)} instances ({len(test_records)/len(records)*100:.1f}%)\")\n",
                "\n",
                "# Print Preprocessing Inspection Examples (Phase 3 Requirement)\n",
                "from transformers import AutoTokenizer\n",
                "tokenizer = AutoTokenizer.from_pretrained('csebuetnlp/banglabert')\n",
                "\n",
                "print(\"\\n=== PHASE 3: TOKENIZATION INSPECTION SAMPLES ===\")\n",
                "for i, r in enumerate(train_records[:3], 1):\n",
                "    enc = tokenizer(r['text'], r['target_word'], truncation=True, max_length=128)\n",
                "    tokens = tokenizer.convert_ids_to_tokens(enc['input_ids'])\n",
                "    print(f\"\\nSample {i}:\")\n",
                "    print(f\"  Target Word:    {r['target_word']}\")\n",
                "    print(f\"  True Sense:     Sense {r['sense_num']} ({r['sense_def']})\")\n",
                "    print(f\"  Context:        {r['text'][:100]}...\")\n",
                "    print(f\"  First 12 Tokens:{tokens[:12]}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 4: Baseline Model — TF-IDF + Linear SVM**\n",
                "### **Why a Per-Word Baseline?**\n",
                "In standard Lexical Sample WSD literature (Navigli 2009, SemEval), sense disambiguation is conditioned on the target word. We train a dedicated Linear SVM for each polysemous word using TF-IDF sub-word / word n-grams.\n",
                "\n",
                "We evaluate across all 690 test instances, and report:\n",
                "* Overall Accuracy, Macro F1, Weighted F1\n",
                "* 3-Sense Words Breakdown (55 words, N=330)\n",
                "* 4-Sense Words Breakdown (45 words, N=360)\n",
                "* Confusion Matrix"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from sklearn.feature_extraction.text import TfidfVectorizer\n",
                "from sklearn.svm import LinearSVC\n",
                "from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix\n",
                "\n",
                "train_by_word = {}\n",
                "for r in train_records:\n",
                "    train_by_word.setdefault(r['folder'], []).append(r)\n",
                "\n",
                "test_by_word = {}\n",
                "for r in test_records:\n",
                "    test_by_word.setdefault(r['folder'], []).append(r)\n",
                "\n",
                "all_y_true, all_y_pred = [], []\n",
                "y_true_3s, y_pred_3s = [], []\n",
                "y_true_4s, y_pred_4s = [], []\n",
                "\n",
                "for folder, test_items in sorted(test_by_word.items()):\n",
                "    train_items = train_by_word.get(folder, [])\n",
                "    if not train_items: continue\n",
                "\n",
                "    X_tr = [r['text'] for r in train_items]\n",
                "    y_tr = [r['sense_label'] for r in train_items]\n",
                "    X_te = [r['text'] for r in test_items]\n",
                "    y_te = [r['sense_label'] for r in test_items]\n",
                "\n",
                "    vec = TfidfVectorizer(ngram_range=(1, 2), sublinear_tf=True)\n",
                "    X_tr_tfidf = vec.fit_transform(X_tr)\n",
                "    X_te_tfidf = vec.transform(X_te)\n",
                "\n",
                "    clf = LinearSVC(C=1.0, loss='squared_hinge', random_state=42, dual='auto')\n",
                "    clf.fit(X_tr_tfidf, y_tr)\n",
                "    preds = clf.predict(X_te_tfidf)\n",
                "\n",
                "    all_y_true.extend(y_te)\n",
                "    all_y_pred.extend(preds)\n",
                "\n",
                "    ns = len(catalog[folder]['senses'])\n",
                "    if ns == 3:\n",
                "        y_true_3s.extend(y_te)\n",
                "        y_pred_3s.extend(preds)\n",
                "    else:\n",
                "        y_true_4s.extend(y_te)\n",
                "        y_pred_4s.extend(preds)\n",
                "\n",
                "svm_acc = accuracy_score(all_y_true, all_y_pred)\n",
                "svm_p_macro, svm_r_macro, svm_f1_macro, _ = precision_recall_fscore_support(all_y_true, all_y_pred, average='macro')\n",
                "svm_p_wt, svm_r_wt, svm_f1_wt, _ = precision_recall_fscore_support(all_y_true, all_y_pred, average='weighted')\n",
                "\n",
                "acc_3s = accuracy_score(y_true_3s, y_pred_3s)\n",
                "_, _, f1_3s_macro, _ = precision_recall_fscore_support(y_true_3s, y_pred_3s, average='macro')\n",
                "\n",
                "acc_4s = accuracy_score(y_true_4s, y_pred_4s)\n",
                "_, _, f1_4s_macro, _ = precision_recall_fscore_support(y_true_4s, y_pred_4s, average='macro')\n",
                "\n",
                "print(\"=======================================================\")\n",
                "print(\"      TF-IDF + LINEAR SVM BASELINE RESULTS             \")\n",
                "print(\"=======================================================\")\n",
                "print(f\"Test Accuracy:    {svm_acc*100:.2f}%\")\n",
                "print(f\"Macro Precision:  {svm_p_macro*100:.2f}%\")\n",
                "print(f\"Macro Recall:     {svm_r_macro*100:.2f}%\")\n",
                "print(f\"Macro F1-Score:   {svm_f1_macro*100:.2f}%\")\n",
                "print(f\"Weighted F1-Score:{svm_f1_wt*100:.2f}%\")\n",
                "print(\"-------------------------------------------------------\")\n",
                "print(f\"3-Sense Words (N={len(y_true_3s)}): Acc = {acc_3s*100:.2f}%, Macro F1 = {f1_3s_macro*100:.2f}%\")\n",
                "print(f\"4-Sense Words (N={len(y_true_4s)}): Acc = {acc_4s*100:.2f}%, Macro F1 = {f1_4s_macro*100:.2f}%\")\n",
                "print(\"=======================================================\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 5 & 6: Pretrained Bengali Transformer (BanglaBERT)**\n",
                "### **Architecture & Candidate Sense Masking**\n",
                "We fine-tune `csebuetnlp/banglabert` with a sequence classification head.\n",
                "- **Input:** `[CLS] context [SEP] target_word [SEP]`\n",
                "- **Candidate Logit Masking:** For 3-sense words, the 4th logit is masked (`logits[:, 3] = -1e9`), strictly confining predictions to valid candidate senses.\n",
                "- **Early Stopping:** Saves best checkpoint based on validation performance."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch.nn as nn\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "from transformers import AutoModelForSequenceClassification, get_linear_schedule_with_warmup\n",
                "\n",
                "class BengaliWSDDataset(Dataset):\n",
                "    def __init__(self, records, tokenizer, max_len=128):\n",
                "        self.records = records\n",
                "        self.tokenizer = tokenizer\n",
                "        self.max_len = max_len\n",
                "\n",
                "    def __len__(self):\n",
                "        return len(self.records)\n",
                "\n",
                "    def __getitem__(self, idx):\n",
                "        item = self.records[idx]\n",
                "        enc = self.tokenizer(\n",
                "            item['text'],\n",
                "            item['target_word'],\n",
                "            max_length=self.max_len,\n",
                "            padding='max_length',\n",
                "            truncation=True,\n",
                "            return_tensors='pt'\n",
                "        )\n",
                "        return {\n",
                "            'input_ids': enc['input_ids'].squeeze(0),\n",
                "            'attention_mask': enc['attention_mask'].squeeze(0),\n",
                "            'token_type_ids': enc['token_type_ids'].squeeze(0) if 'token_type_ids' in enc else torch.zeros(self.max_len, dtype=torch.long),\n",
                "            'label': torch.tensor(item['sense_label'], dtype=torch.long),\n",
                "            'num_senses': torch.tensor(item['num_senses_for_word'], dtype=torch.long)\n",
                "        }\n",
                "\n",
                "class BanglaBERTWSD(nn.Module):\n",
                "    def __init__(self, model_name='csebuetnlp/banglabert', num_labels=4):\n",
                "        super().__init__()\n",
                "        self.transformer = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)\n",
                "\n",
                "    def forward(self, input_ids, attention_mask, token_type_ids=None, num_senses=None):\n",
                "        logits = self.transformer(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids).logits\n",
                "        if num_senses is not None:\n",
                "            mask = torch.zeros_like(logits)\n",
                "            for b, n in enumerate(num_senses):\n",
                "                if n == 3: mask[b, 3] = -1e9\n",
                "            logits = logits + mask\n",
                "        return logits\n",
                "\n",
                "BATCH_SIZE = 16\n",
                "EPOCHS = 4\n",
                "LR = 2e-5\n",
                "\n",
                "train_ds = BengaliWSDDataset(train_records, tokenizer)\n",
                "val_ds   = BengaliWSDDataset(val_records, tokenizer)\n",
                "test_ds  = BengaliWSDDataset(test_records, tokenizer)\n",
                "\n",
                "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)\n",
                "val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
                "test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
                "\n",
                "model = BanglaBERTWSD().to(device)\n",
                "optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=0.01)\n",
                "total_steps = len(train_loader) * EPOCHS\n",
                "scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=int(total_steps*0.1), num_training_steps=total_steps)\n",
                "criterion = nn.CrossEntropyLoss()\n",
                "\n",
                "best_val_acc = 0.0\n",
                "print(\"Starting BanglaBERT Fine-Tuning...\")\n",
                "for epoch in range(1, EPOCHS + 1):\n",
                "    model.train()\n",
                "    total_loss, tr_preds, tr_labels = 0.0, [], []\n",
                "    for batch in train_loader:\n",
                "        optimizer.zero_grad()\n",
                "        ids = batch['input_ids'].to(device)\n",
                "        mask = batch['attention_mask'].to(device)\n",
                "        tt = batch['token_type_ids'].to(device)\n",
                "        lbl = batch['label'].to(device)\n",
                "        ns = batch['num_senses'].to(device)\n",
                "        logits = model(ids, mask, tt, ns)\n",
                "        loss = criterion(logits, lbl)\n",
                "        loss.backward()\n",
                "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
                "        optimizer.step()\n",
                "        scheduler.step()\n",
                "        total_loss += loss.item() * len(lbl)\n",
                "        tr_preds.extend(torch.argmax(logits, dim=-1).cpu().numpy())\n",
                "        tr_labels.extend(lbl.cpu().numpy())\n",
                "    tr_loss = total_loss / len(tr_labels)\n",
                "    tr_acc = accuracy_score(tr_labels, tr_preds)\n",
                "\n",
                "    # Validation\n",
                "    model.eval()\n",
                "    val_loss, val_preds, val_labels = 0.0, [], []\n",
                "    with torch.no_grad():\n",
                "        for batch in val_loader:\n",
                "            ids = batch['input_ids'].to(device)\n",
                "            mask = batch['attention_mask'].to(device)\n",
                "            tt = batch['token_type_ids'].to(device)\n",
                "            lbl = batch['label'].to(device)\n",
                "            ns = batch['num_senses'].to(device)\n",
                "            logits = model(ids, mask, tt, ns)\n",
                "            val_loss += criterion(logits, lbl).item() * len(lbl)\n",
                "            val_preds.extend(torch.argmax(logits, dim=-1).cpu().numpy())\n",
                "            val_labels.extend(lbl.cpu().numpy())\n",
                "    val_loss /= len(val_labels)\n",
                "    val_acc = accuracy_score(val_labels, val_preds)\n",
                "    print(f\"Epoch {epoch}/{EPOCHS} | Train Loss: {tr_loss:.4f}, Train Acc: {tr_acc*100:.2f}% | Val Loss: {val_loss:.4f}, Val Acc: {val_acc*100:.2f}%\")\n",
                "    if val_acc > best_val_acc:\n",
                "        best_val_acc = val_acc\n",
                "        torch.save(model.state_dict(), 'best_banglabert.pt')\n",
                "print(f\"Training finished! Best Validation Accuracy: {best_val_acc*100:.2f}%\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 7 & 8: Final Test Evaluation & Error Analysis**\n",
                "We evaluate the best saved checkpoint once on the held-out test set."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if os.path.exists('best_banglabert.pt'):\n",
                "    model.load_state_dict(torch.load('best_banglabert.pt', map_location=device))\n",
                "model.eval()\n",
                "\n",
                "test_y_true, test_y_pred, test_confs = [], [], []\n",
                "t_true_3s, t_pred_3s = [], []\n",
                "t_true_4s, t_pred_4s = [], []\n",
                "test_errors = []\n",
                "\n",
                "with torch.no_grad():\n",
                "    for idx, batch in enumerate(test_loader):\n",
                "        ids = batch['input_ids'].to(device)\n",
                "        mask = batch['attention_mask'].to(device)\n",
                "        tt = batch['token_type_ids'].to(device)\n",
                "        lbl = batch['label'].to(device)\n",
                "        ns = batch['num_senses'].to(device)\n",
                "\n",
                "        logits = model(ids, mask, tt, ns)\n",
                "        probs = torch.softmax(logits, dim=-1)\n",
                "        preds = torch.argmax(probs, dim=-1)\n",
                "        confs, _ = torch.max(probs, dim=-1)\n",
                "\n",
                "        lbl_np = lbl.cpu().numpy()\n",
                "        preds_np = preds.cpu().numpy()\n",
                "        confs_np = confs.cpu().numpy()\n",
                "        ns_np = ns.cpu().numpy()\n",
                "\n",
                "        test_y_true.extend(lbl_np)\n",
                "        test_y_pred.extend(preds_np)\n",
                "        test_confs.extend(confs_np)\n",
                "\n",
                "        for i in range(len(lbl_np)):\n",
                "            if ns_np[i] == 3:\n",
                "                t_true_3s.append(lbl_np[i])\n",
                "                t_pred_3s.append(preds_np[i])\n",
                "            else:\n",
                "                t_true_4s.append(lbl_np[i])\n",
                "                t_pred_4s.append(preds_np[i])\n",
                "\n",
                "            if lbl_np[i] != preds_np[i]:\n",
                "                raw_item = test_records[idx * BATCH_SIZE + i]\n",
                "                test_errors.append({\n",
                "                    'target': raw_item['target_word'],\n",
                "                    'context': raw_item['text'],\n",
                "                    'true_sense': raw_item['sense_num'],\n",
                "                    'true_def': raw_item['sense_def'],\n",
                "                    'pred_sense': preds_np[i] + 1,\n",
                "                    'conf': confs_np[i]\n",
                "                })\n",
                "\n",
                "trans_acc = accuracy_score(test_y_true, test_y_pred)\n",
                "trans_p_m, trans_r_m, trans_f1_m, _ = precision_recall_fscore_support(test_y_true, test_y_pred, average='macro')\n",
                "trans_p_w, trans_r_w, trans_f1_w, _ = precision_recall_fscore_support(test_y_true, test_y_pred, average='weighted')\n",
                "\n",
                "t_acc_3s = accuracy_score(t_true_3s, t_pred_3s)\n",
                "_, _, t_f1_3s, _ = precision_recall_fscore_support(t_true_3s, t_pred_3s, average='macro')\n",
                "t_acc_4s = accuracy_score(t_true_4s, t_pred_4s)\n",
                "_, _, t_f1_4s, _ = precision_recall_fscore_support(t_true_4s, t_pred_4s, average='macro')\n",
                "\n",
                "print(\"=======================================================\")\n",
                "print(\"      BANGLABERT TRANSFORMER TEST RESULTS              \")\n",
                "print(\"=======================================================\")\n",
                "print(f\"Test Accuracy:    {trans_acc*100:.2f}%\")\n",
                "print(f\"Macro Precision:  {trans_p_m*100:.2f}%\")\n",
                "print(f\"Macro Recall:     {trans_r_m*100:.2f}%\")\n",
                "print(f\"Macro F1-Score:   {trans_f1_m*100:.2f}%\")\n",
                "print(f\"Weighted F1-Score:{trans_f1_w*100:.2f}%\")\n",
                "print(\"-------------------------------------------------------\")\n",
                "print(f\"3-Sense Words (N={len(t_true_3s)}): Acc = {t_acc_3s*100:.2f}%, Macro F1 = {t_f1_3s*100:.2f}%\")\n",
                "print(f\"4-Sense Words (N={len(t_true_4s)}): Acc = {t_acc_4s*100:.2f}%, Macro F1 = {t_f1_4s*100:.2f}%\")\n",
                "print(\"=======================================================\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### **Sample Error Cases (Phase 8 Requirement)**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "print(\"=== SAMPLE ERROR DIAGNOSTICS ===\")\n",
                "for i, err in enumerate(test_errors[:5], 1):\n",
                "    print(f\"\\nError Case {i}:\")\n",
                "    print(f\"  Target Word:          {err['target']}\")\n",
                "    print(f\"  Context Snippet:      {err['context'][:120]}...\")\n",
                "    print(f\"  True Sense:           Sense {err['true_sense']} ({err['true_def']})\")\n",
                "    print(f\"  Predicted Sense:      Sense {err['pred_sense']}\")\n",
                "    print(f\"  Prediction Confidence:{err['conf']*100:.1f}%\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## **Stage 9: Model Comparison & Scientific Conclusions**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "\n",
                "comp_data = [\n",
                "    {\n",
                "        'Model': 'TF-IDF + Linear SVM',\n",
                "        'Accuracy': f\"{svm_acc*100:.2f}%\",\n",
                "        'Macro F1': f\"{svm_f1_macro*100:.2f}%\",\n",
                "        'Weighted F1': f\"{svm_f1_wt*100:.2f}%\"\n",
                "    },\n",
                "    {\n",
                "        'Model': 'BanglaBERT Transformer',\n",
                "        'Accuracy': f\"{trans_acc*100:.2f}%\",\n",
                "        'Macro F1': f\"{trans_f1_m*100:.2f}%\",\n",
                "        'Weighted F1': f\"{trans_f1_w*100:.2f}%\"\n",
                "    }\n",
                "]\n",
                "print(\"=== OVERALL PERFORMANCE COMPARISON ===\")\n",
                "display(pd.DataFrame(comp_data))\n",
                "\n",
                "complexity_data = [\n",
                "    {\n",
                "        'Word Complexity': '3 Senses (55 words)',\n",
                "        'SVM Accuracy': f\"{acc_3s*100:.2f}%\",\n",
                "        'SVM Macro F1': f\"{f1_3s_macro*100:.2f}%\",\n",
                "        'Transformer Accuracy': f\"{t_acc_3s*100:.2f}%\",\n",
                "        'Transformer Macro F1': f\"{t_f1_3s*100:.2f}%\"\n",
                "    },\n",
                "    {\n",
                "        'Word Complexity': '4 Senses (45 words)',\n",
                "        'SVM Accuracy': f\"{acc_4s*100:.2f}%\",\n",
                "        'SVM Macro F1': f\"{f1_4s_macro*100:.2f}%\",\n",
                "        'Transformer Accuracy': f\"{t_acc_4s*100:.2f}%\",\n",
                "        'Transformer Macro F1': f\"{t_f1_4s*100:.2f}%\"\n",
                "    }\n",
                "]\n",
                "print(\"\\n=== COMPLEXITY BREAKDOWN (3 SENSES VS 4 SENSES) ===\")\n",
                "display(pd.DataFrame(complexity_data))"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "gpuType": "T4",
            "provenance": []
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = r"e:\ArthoBodh\ArthoBodh_WSD_Colab.ipynb"
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=2)

print("Generated self-contained Google Colab notebook at:", out_path)
